"""remove unique constraint from role

Revision ID: cd2e2b13c83e
Revises: 660ad4933026
Create Date: 2026-03-02 17:14:59.502770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd2e2b13c83e'
down_revision: Union[str, Sequence[str], None] = '660ad4933026'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('role'), table_name='roles')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('role'), 'roles', ['role'], unique=True)
    # ### end Alembic commands ###
